### ISSUE TITLE
[doc] add faq of the difference between pattern object and pattern+kind

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep.github.io#554]
User will write this and hope tree-sitter will parse it as class field

```yaml
pattern: a = 123
kind: class_field
```

but it does not work

```yaml
pattern:
  context: a = 123
  selector: class_field
```

this should work
