### ISSUE TITLE
[doc] add cpp example changing sprintf

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep.github.io#633]
```
ast-grep scan --update-all --inline-rules '
id: fix-format-security-error
language: Cpp
rule:
  any:
    - pattern: $PRINTF($A, $B)
constraints:
  PRINTF:
    { regex: "^.printf$" }
  B:
    not:
      any:
        - { kind: string_literal }
        - { kind: concatenated_string }
        - { regex: "^[A-Z_]+$" } # ignore macros
fix:
  $PRINTF($A, "%s", $B)
'
```

created by @xiaoxiangmoe
