### ISSUE TITLE
blog: add rule / file simplification example

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep.github.io#664]
https://github.com/ast-grep/ast-grep/issues/1779#issuecomment-2623128947

**Comment by HerringtonDarkholme** [comment]
Another example


```
id: some_sqli_rule
language: python
rule:
  pattern: $X.execute($$$)
  has:
    kind: argument_list
    has:
      nthChild: 1
      any:
        - kind: identifier
          pattern: $VAR
        - has:
            stopBy: end
            kind: identifier
            pattern: $VAR
  inside:
    stopBy: end
    kind: module
    has:
      stopBy: end
      kind: assignment
      pattern: $VAR = $$$
```

```
something = "value" # If has comment it does catch the vulnerable line

vuln_param = other

x.execute(f"DROP TABLE IF EXISTS {vuln_param}") # Vulnreable
```
