### ISSUE TITLE
catalog: add ts inreference example

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep.github.io#696]
ast-grep scan -r unnecessary-declaration-annotation.yml -U
```
id: unnecessary-declaration-annotation
language: typescript
rule:
  kind: type_annotation
  inside:
    kind: variable_declarator
    has:
      field: value
      any:
      - kind: await_expression
      - kind: new_expression
```
