### ISSUE TITLE
doc: add documentation for custom language registration

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep.github.io#98]
1. Compile tree-sitter as dynamic language. https://github.com/ast-grep/ast-grep/discussions/351
2. Register the language in sgconfig.yml
```yml
customLanguages:
  mojo:
      libraryPath: mojo.so # path to dynamic lib
      extensions: [mojo]
      # expandoChar: optional character to replace metavariable $ in your pattern
```
3. Now you can use it!
